### ISSUE TITLE
Separate token generation and token checking

### ISSUE THREAD

**Issue by mj4444ru** [yiisoft/csrf#12]
Why generate a token here: ?

https://github.com/yiisoft/csrf/blob/5f442d47f0c64e07815f2eda0d0194bb1146d9d0/src/CsrfMiddleware.php#L67-L76

If you can generate here:

https://github.com/yiisoft/csrf/blob/5f442d47f0c64e07815f2eda0d0194bb1146d9d0/src/CsrfToken.php#L25-L33

In this case, the token will be generated on the first use, not on the first request.

**Comment by vjik** [comment]
`CsrfToken::getValue()` used to get token for send via request. Missing token should throw an exception, not generate a new token.

**Comment by mj4444ru** [comment]
Why should I throw an exception?

**Comment by vjik** [comment]
> Why should I throw an exception?

For example, exception can show that you not connected middleware.

**Comment by mj4444ru** [comment]
> > Why should I throw an exception?
> 
> For example, exception can show that you not connected middleware.

For example, I don't want to include this middleware in my API, but I want to generate a token for the Web.
For some other reason, I cannot connect this middleware, but I want to generate a token for the Web.
What should I do?

**Comment by vjik** [comment]
Why do you need a token if you don't check it?

**Comment by mj4444ru** [comment]
I need a token because I check it. You have strange statements.

**Comment by vjik** [comment]
> I need a token because I check it. You have strange statements.

You should check and then create/save new token before use token in web.

**Comment by mj4444ru** [comment]
> > I need a token because I check it. You have strange statements.
> 
> You should check and then create/save new token before use token in web.

Why should I do what you say, and not what the business logic of the application needs?

**Comment by mj4444ru** [comment]
The simplest example:
On the site for guests, a session is not created, since nothing is stored in it. If the guest performs any specific action, data is placed in the session and session it is automatically created. With this csrf validator, the session will always be created when opening the first page, but this is not necessary.

I do not consider it necessary to continue the discussion further.

**Comment by samdark** [comment]
We need an ability to enable/disable token generation for certain condition.

**Comment by mj4444ru** [comment]
> We need an ability to enable/disable token generation for certain condition.

It's too complicated.
As I already gave an example, it is possible that the verification of the token should be skipped, but we still need the token.
A token should only be generated when needed.
You don't have to do what is not required.

**Comment by samdark** [comment]
> A token should only be generated when needed.

Is there a certain way to check if token will be needed? For example, it's a GET request and we have a form somewhere in the page. Token should be generated. If it's a GET request and there are no forms at all, it still may be needed for some custom JavaScript that reads token from a meta-tag and does POST request.

**Comment by mj4444ru** [comment]
> > A token should only be generated when needed.
> 
> Is there a certain way to check if token will be needed? For example, it's a GET request and we have a form somewhere in the page. Token should be generated. If it's a GET request and there are no forms at all, it still may be needed for some custom JavaScript that reads token from a meta-tag and does POST request.

The example is incorrect. JavaScript has nothing to do with middleware.
If JavaScript requires a token, it must be provided in some form on the page. One way to do this is to pass it through the meta tag. In this case, the token will be generated when generating the page template (on request).

**Comment by samdark** [comment]
https://github.com/yiisoft/csrf/issues/15 should be done first. Then this issue may become obsolete because there will be no sense in not executing the middleware.

**Comment by mj4444ru** [comment]
> #15 should be done first. Then this issue may become obsolete because there will be no sense in not executing the middleware.

Changing the way the token is generated does not solve the 2 aforementioned problems.

**Comment by samdark** [comment]
Likely not but we'll see.
