### ISSUE TITLE
Add ability to exclude / include URLs from CSRF protection

### ISSUE THREAD

**Issue by samdark** [yiisoft/csrf#14]
Usually the middleware is enabled globally. Need to add a way to exclude certain URLs or include only certain URL.

**Comment by samdark** [comment]
Related to https://github.com/yiisoft/csrf/issues/12 where we need similar ability but based on authentication.

**Comment by vjik** [comment]
Hm... maybe this ability should by globaly for any middleware?

**Comment by samdark** [comment]
Likely not. Many middleware are meant to be attached to router groups/routes, some are alright to be always executed.

**Comment by samdark** [comment]
Could be achieved now by disabling middleware via router config.
